const int led1=5;
const int led2=6;
const int led3=7;
const int led4=8;
const int led5=9;
const int led6=10;
const int led7=11;
const int led8=12;
unsigned long ret=500;

void setup() {

pinMode(led1, OUTPUT);
pinMode(led2, OUTPUT);
pinMode(led3, OUTPUT);
pinMode(led4, OUTPUT);
pinMode(led5, OUTPUT);
pinMode(led6, OUTPUT);
pinMode(led7, OUTPUT);
pinMode(led8, OUTPUT);

}
void loop() {
  
digitalWrite(led1, 0);
digitalWrite(led2, 1);
digitalWrite(led3, 1);
digitalWrite(led4, 1);
digitalWrite(led5, 1);
digitalWrite(led6, 1);
digitalWrite(led7, 1);
digitalWrite(led8, 0);
delay(ret);
digitalWrite(led1, 0);
digitalWrite(led2, 1);
digitalWrite(led3, 0);
digitalWrite(led4, 0);
digitalWrite(led5, 1);
digitalWrite(led6, 0);
digitalWrite(led7, 0);
digitalWrite(led8, 0);
delay(ret);
digitalWrite(led1, 1);
digitalWrite(led2, 0);
digitalWrite(led3, 1);
digitalWrite(led4, 1);
digitalWrite(led5, 5);
digitalWrite(led6, 6);
digitalWrite(led7, 0);
digitalWrite(led8, 0);
delay(ret);
digitalWrite(led1, 1);
digitalWrite(led2, 0);
digitalWrite(led3, 1);
digitalWrite(led4, 1);
digitalWrite(led5, 0);
digitalWrite(led6, 1);
digitalWrite(led7, 1);
digitalWrite(led8, 0);
delay(ret);
digitalWrite(led1, 1);
digitalWrite(led2, 1);
digitalWrite(led3, 0);
digitalWrite(led4, 1);
digitalWrite(led5, 0);
digitalWrite(led6, 0);
digitalWrite(led7, 1);
digitalWrite(led8, 0);
delay(ret);
digitalWrite(led1, 1);
digitalWrite(led2, 1);
digitalWrite(led3, 1);
digitalWrite(led4, 0);
digitalWrite(led5, 0);
digitalWrite(led6, 1);
digitalWrite(led7, 1);
digitalWrite(led8, 0);
delay(ret);
digitalWrite(led1, 1);
digitalWrite(led2, 1);
digitalWrite(led3, 0);
digitalWrite(led4, 0);
digitalWrite(led5, 1);
digitalWrite(led6, 1);
digitalWrite(led7, 1);
digitalWrite(led8, 0);
delay(ret);
digitalWrite(led1, 0);
digitalWrite(led2, 0);
digitalWrite(led3, 1);
digitalWrite(led4, 1);
digitalWrite(led5, 0);
digitalWrite(led6, 0);
digitalWrite(led7, 1);
digitalWrite(led8, 0);
delay(ret);
digitalWrite(led1, 1);
digitalWrite(led2, 1);
digitalWrite(led3, 1);
digitalWrite(led4, 1);
digitalWrite(led5, 1);
digitalWrite(led6, 1);
digitalWrite(led7, 1);
digitalWrite(led8, 0);
delay(ret);
digitalWrite(led1, 1);
digitalWrite(led2, 1);
digitalWrite(led3, 1);
digitalWrite(led4, 1);
digitalWrite(led5, 0);
digitalWrite(led6, 0);
digitalWrite(led7, 1);
digitalWrite(led8, 0);
delay(ret);
digitalWrite(led1, 0);
digitalWrite(led2, 0);
digitalWrite(led3, 0);
digitalWrite(led4, 0);
digitalWrite(led5, 0);
digitalWrite(led6, 0);
digitalWrite(led7, 0);
digitalWrite(led8, 1);
delay(ret);
}
